<h1 style="
  font-family: 'Montserrat', sans-serif; 
  font-weight: 700; 
  text-align: center; 
  color: #22304a; 
  text-shadow: 2px 2px 8px rgba(0,0,0,0.15); 
  font-size: 3.5em; 
  margin-bottom: 0.3em;
">
  TUTORIAL COMPLETO Y MINUCIOSO SOBRE NUMPY, LA BIBLIOTECA DE PYTHON PARA CÁLCULO NUMÉRICO Y MANIPULACIÓN DE ARRAYS 📊🐍🔢
</h1>

---

<h2 style="
  font-family: 'Lato', sans-serif; 
  font-weight: 600; 
  text-align: center; 
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34); 
  font-size: 2.8em; 
  color: #22304a;
  margin-top: 0; 
  margin-bottom: 1em;
">
  ¡DOMINA NUMPY YA! 🚀📊🔢 APRENDE A MANIPULAR ARRAYS Y CALCULAR CON MÁXIMA EFICIENCIA EN PYTHON.
</h2>

---

<p style="
  font-family: 'Lato', sans-serif; 
  font-weight: 600; 
  font-size: 1.8em; 
  text-align: justify; 
  color: #22304a;
  margin-top: 0; 
  margin-bottom: 1em;
">
  Por: Marco Antonio Cornejo Jaramillo BEng.(HONS) MSc.
</p>

---

<section style="
  font-family: 'Raleway', sans-serif; 
  font-weight: 500; 
  text-align: justify; 
  font-size: 1.1em; 
  color: #33475b;
  margin-bottom: 2em;
">
  <h3 style="font-weight: 700; margin-bottom: 0.3em;">Contacto:</h3>

  <p style="margin: 0.2em 0;">
    <a href="mailto:marcoantoniocornejojaramillo.13@gmail.com" style="color:#1a73e8; text-decoration: none;">Email</a><br>
    <a href="https://www.linkedin.com/in/marcoantoniocornejoingenieroyprogramador" style="color:#1a73e8; text-decoration: none;">Linkedin Perfil</a><br>
    <a href="https://github.com/diode23" style="color:#1a73e8; text-decoration: none;">Github Perfil</a><br>
    <a href="https://linktr.ee/marcoantoniocornejojaramillo" style="color:#1a73e8; text-decoration: none;">Todos mis Enlaces</a><br>
    Número de Teléfono Móvil: +58 412 249 42 72
  </p>
</section>

---

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  ¿Quieres llevar tus habilidades en Python al siguiente nivel y convertirte en un experto en cálculo numérico y manipulación de datos? 💻📈 ¡Estás en el lugar indicado! NumPy es la biblioteca esencial para cualquier programador, científico de datos o analista que busque realizar operaciones complejas con rapidez y precisión. 🧮🔍 En este tutorial completo y minucioso descubrirás desde la instalación y configuración, hasta técnicas avanzadas como broadcasting y álgebra lineal. ¿Cómo puedes aprovechar las funciones vectorizadas para crear algoritmos innovadores y eficientes? 🤔⚡ ¿Quieres entender la importancia de aprovechar soluciones robustas para optimizar tus proyectos de ciencia de datos y simulación numérica? Este contenido está diseñado para que domines absolutamente todo sobre NumPy, aplicándolo en casos reales y prácticos que potenciarán tus resultados. 🌟📊 ¡No pierdas la oportunidad de transformar la manera en la que gestionas y analizas datos con Python! Sigue leyendo y prepárate para un viaje lleno de conocimiento imprescindible que revolucionará tu código y productividad. 🚀🔢
</p>

---

---

<h1 style="
  font-family: 'Montserrat', sans-serif;
  font-weight: 700;
  text-align: center;
  color: #3c5a80;
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34);
  font-size: 2.5em;
  margin-bottom: 0.5em;
">
  1. Introducción
</h1>

<h2 style="
  font-family: 'Lato', sans-serif;
  font-weight: 600;
  text-align: justify;
  color: #3c5a80;
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34);
  font-size: 1.8em;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  1.1 ¿Qué es NumPy?
</h2>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
">
  NumPy (Numerical Python) es una biblioteca esencial para el lenguaje de programación Python que proporciona soporte para arrays multidimensionales y una amplia colección de funciones matemáticas para realizar cálculos de alto rendimiento y manipular grandes volúmenes de datos numéricos (Oliphant, 2006). A diferencia de las listas nativas de Python, que son flexibles pero más lentas y menos eficientes para cálculos masivos, NumPy está optimizada para operaciones vectorizadas, facilitando tareas numéricas que van desde álgebra lineal hasta análisis estadístico.
</p>


<h2 style="
  font-family: 'Lato', sans-serif;
  font-weight: 600;
  text-align: justify;
  color: #3c5a80;
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34);
  font-size: 1.8em;
  margin-bottom: 0.7em;
  margin-top: 0;
">
  1.2 ¿Para qué sirve NumPy?
</h2>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  NumPy es fundamental para tareas de:
</p>

<ul style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  padding-left: 1.2em;
  margin-bottom: 0;
">
  <li>Cálculo científico y técnico.</li>
  <li>Manipulación eficiente de arrays grandes en memoria.</li>
  <li>Optimización de operaciones matemáticas sin necesidad de usar bucles explícitos en Python (operaciones vectorizadas).</li>
  <li>Base para otras bibliotecas populares como Pandas, SciPy, Matplotlib y frameworks de aprendizaje automático.</li>
</ul>

<h2 style="
  font-family: 'Lato', sans-serif;
  font-weight: 600;
  text-align: justify;
  color: #3c5a80;
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34);
  font-size: 1.8em;
  margin-bottom: 0.7em;
  margin-top: 0;
">
  1.3 Ventajas principales de NumPy.
</h2>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  NumPy es fundamental para tareas de:
</p>

<ul style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  padding-left: 1.2em;
  margin-bottom: 1.5em;
">
  <li>Eficiencia en tiempo y memoria: Implementación en C y Fortran, muy eficiente para datos numéricos.</li>
  <li>Compatibilidad y ecosistema: Trabaja de forma integrada con otras bibliotecas del entorno científico.</li>
  <li>Broadcasting: Permite operar arrays de diferente forma sin necesidad de replicar datos.</li>
  <li>Facilidad de aprendizaje: Sintaxis clara y estructura lógica.</li>
</ul>

---

<h1 style="
  font-family: 'Montserrat', sans-serif;
  font-weight: 700;
  text-align: center;
  color: #3c5a80;
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34);
  font-size: 2.5em;
  margin-bottom: 0.5em;
">
  2. Desarrollo.
</h1>

<h2 style="
  font-family: 'Lato', sans-serif; 
  font-weight: 600; 
  text-align: justify; 
  color: #3c5a80; 
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34); 
  font-size: 1.8em; 
  margin-top: 0; 
  margin-bottom: 0.7em;
">
  2.1 Instalación y Configuración.
</h2>

<h3 style="
  font-family: 'Lato', sans-serif; 
  font-weight: 600; 
  text-align: justify; 
  color: #3c5a80; 
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34); 
  font-size: 1.4em; 
  margin-top: 0; 
  margin-bottom: 0.7em;
">
  2.1.1 Instalación mediante pip.
</h3>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
Para instalar NumPy, lo más habitual es usar el gestor de paquetes pip. Abra su terminal o consola y ejecute:
</p>

In [ ]:
# bash

pip install numpy

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
En entornos como Anaconda, NumPy ya viene preinstalado.
</p>

<h3 style="
  font-family: 'Lato', sans-serif; 
  font-weight: 600; 
  text-align: justify; 
  color: #3c5a80; 
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34); 
  font-size: 1.4em; 
  margin-top: 0; 
  margin-bottom: 0.7em;
">
  2.1.2 Verificación de la instalación.
</h3>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
Una vez instalada, verifique importándola desde un intérprete Python con:
</p>

In [ ]:
# Python

import numpy as np
print(np.__version__)

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
Si este código muestra la versión instalada sin errores, NumPy está correctamente instalado.
</p>

---

<h2 style="
  font-family: 'Lato', sans-serif; 
  font-weight: 600; 
  text-align: justify; 
  color: #3c5a80; 
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34); 
  font-size: 1.8em; 
  margin-top: 0; 
  margin-bottom: 0.7em;
">
  2.2 Creación y Manipulación Básica de Arrays.
</h2>

<h3 style="
  font-family: 'Lato', sans-serif; 
  font-weight: 600; 
  text-align: justify; 
  color: #3c5a80; 
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34); 
  font-size: 1.4em; 
  margin-top: 0; 
  margin-bottom: 0.7em;
">
  2.2.1 Definición de arrays en NumPy.
</h3>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  El objeto principal en NumPy es el array (ndarray), una estructura homogénea (todos elementos del mismo tipo) que puede tener una o varias dimensiones.
</p>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
Crear un array a partir de una lista Python:
</p>

In [ ]:
# Python

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  Salida:
</p>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  text
    
[1 2 3 4 5]
</p>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
Para un array bidimensional:
</p>

In [ ]:
# Python

arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  Salida:
</p>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
text
    
[[1 2 3]
 [4 5 6]]
</p>

<h3 style="
  font-family: 'Lato', sans-serif; 
  font-weight: 600; 
  text-align: justify; 
  color: #3c5a80; 
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34); 
  font-size: 1.4em; 
  margin-top: 0; 
  margin-bottom: 0.7em;
">
  2.2.2 Tipos de datos y dimensiones.
</h3>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  Al crear arrays, puede especificar el tipo de dato usando el parámetro dtype; por ejemplo:
</p>

In [ ]:
# Python

arr_float = np.array([1, 2, 3], dtype=float)
print(arr_float)

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  Tipos comunes:
</p>

<ul style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  padding-left: 1.2em;
  margin-bottom: 1.5em;
">
  <li><code>int</code> (enteros)</li>
  <li><code>float</code> (flotantes)</li>
  <li><code>bool</code> (booleanos)</li>
  <li><code>complex</code> (complejos)</li>
</ul>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  La dimensión o número de ejes del array es accesible con <code>.ndim</code>, y la forma o tamaño por eje con <code>.shape</code>.
</p>

In [ ]:
# Python

print(arr2d.ndim)   # 2
print(arr2d.shape)  # (2, 3)

<h3 style="
  font-family: 'Lato', sans-serif; 
  font-weight: 600; 
  text-align: justify; 
  color: #3c5a80; 
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34); 
  font-size: 1.4em; 
  margin-top: 0; 
  margin-bottom: 0.7em;
">
  2.2.3 Métodos comunes para crear arrays
</h3>

<ul style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  padding-left: 1.2em;
  margin-bottom: 1.5em;
">
  <li><code>np.zeros(shape)</code> – array de ceros.</li>
  <li><code>np.ones(shape)</code> – array de unos.</li>
  <li><code>np.arange(start, stop, step)</code> – valores equidistantes (similar a <code>range</code>).</li>
  <li><code>np.linspace(start, stop, num)</code> – <code>num</code> puntos linealmente espaciados.</li>
  <li><code>np.eye(n)</code> – matriz identidad <code>n×n</code>.</li>
</ul>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  Ejemplos:
</p>


In [ ]:
# Python

print(np.zeros((2,3)))
print(np.ones(5))
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))
print(np.eye(3))

<h3 style="
  font-family: 'Lato', sans-serif;
  font-weight: 600;
  text-align: justify;
  color: #3c5a80;
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34);
  font-size: 1.4em;
  margin-top: 1.2em;
  margin-bottom: 0.8em;
">
  2.2.4 Propiedades básicas de los arrays
</h3>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  Algunas propiedades útiles:
</p>

<ul style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  padding-left: 1.2em;
  margin-bottom: 1.5em;
">
  <li><code>arr.size</code> – número total de elementos.</li>
  <li><code>arr.shape</code> – dimensiones.</li>
  <li><code>arr.dtype</code> – tipo de dato.</li>
  <li><code>arr.itemsize</code> – bytes por elemento.</li>
  <li><code>arr.nbytes</code> – bytes totales.</li>
</ul>

---

<h2 style="
  font-family: 'Lato', sans-serif; 
  font-weight: 600; 
  text-align: justify; 
  color: #3c5a80; 
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34); 
  font-size: 1.8em; 
  margin-top: 0; 
  margin-bottom: 0.7em;
">
  2.3 Funciones Matemáticas y Operaciones Básicas.
</h2>

<h3 style="
  font-family: 'Lato', sans-serif; 
  font-weight: 600; 
  text-align: justify; 
  color: #3c5a80; 
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34); 
  font-size: 1.4em; 
  margin-top: 0; 
  margin-bottom: 0.7em;
">
  2.3.1 Operaciones aritméticas elementales.
</h3>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  NumPy soporta operaciones vectorizadas para arrays del mismo tamaño:
</p>

In [ ]:
# Python

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)    # Suma elemento a elemento
print(a - b)    # Resta
print(a * b)    # Multiplicación
print(a / b)    # División
print(a ** 2)   # Potencia

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  Salida:
</p>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
text
    
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
</p>

<h3 style="
  font-family: 'Lato', sans-serif;
  font-weight: 600;
  text-align: justify;
  color: #3c5a80;
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34);
  font-size: 1.4em;
  margin-top: 1.2em;
  margin-bottom: 0.7em;
">
  2.3.2 Funciones universales (ufuncs)
</h3>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  NumPy ofrece funciones matemáticas que operan elemento a elemento, incluyendo:
</p>

<ul style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  padding-left: 1.2em;
  margin-bottom: 1.5em;
">
  <li><code>np.sqrt(x)</code> – raíz cuadrada.</li>
  <li><code>np.exp(x)</code> – función exponencial <em>exp</em>.</li>
  <li><code>np.log(x)</code> – logaritmo natural.</li>
  <li><code>np.sin(x)</code>, <code>np.cos(x)</code>, <code>np.tan(x)</code> – funciones trigonométricas.</li>
</ul>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  Ejemplo:
</p>

In [ ]:
x = np.array([0, np.pi/2, np.pi])
print(np.sin(x))


<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  Salida:
</p>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
text
    
[0.000000e+00 1.000000e+00 1.224647e-16]
</p>

<h3 style="
  font-family: 'Lato', sans-serif;
  font-weight: 600;
  text-align: justify;
  color: #3c5a80;
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34);
  font-size: 1.4em;
  margin-top: 1.2em;
  margin-bottom: 0.7em;
">
  2.3.3 Funciones estadísticas básicas
</h3>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  NumPy incluye estadísticas simples:
</p>

<ul style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  padding-left: 1.2em;
  margin-bottom: 1.5em;
">
  <li><code>np.min(arr)</code>, <code>np.max(arr)</code></li>
  <li><code>np.mean(arr)</code></li>
  <li><code>np.median(arr)</code> (requiere importar desde numpy)</li>
  <li><code>np.std(arr)</code> (desviación estándar)</li>
  <li><code>np.sum(arr)</code></li>
  <li><code>np.cumsum(arr)</code> (suma acumulativa)</li>
</ul>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  Estas funciones pueden aplicarse a ejes específicos:
</p>

In [ ]:
# Python 

mat = np.array([[1,2,3],[4,5,6]])
print(np.sum(mat, axis=0))  # suma columnas
print(np.sum(mat, axis=1))  # suma filas

---

<h2 style="
  font-family: 'Lato', sans-serif; 
  font-weight: 600; 
  text-align: justify; 
  color: #3c5a80; 
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34); 
  font-size: 1.8em; 
  margin-top: 0; 
  margin-bottom: 0.7em;
">
  2.4 Indexación y Selección Avanzada
</h2>

<h3 style="
  font-family: 'Lato', sans-serif;
  font-weight: 600;
  text-align: justify;
  color: #3c5a80;
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34);
  font-size: 1.4em;
  margin-top: 1em;
  margin-bottom: 0.7em;
">
  2.4.1 Indexación básica y slicing
</h3>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  Los arrays se indexan usando corchetes y posición basada en cero:
</p>

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[2])    # 30
print(arr[-1])   # 50 (último elemento)

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  Para arrays multidimensionales:
</p>

In [ ]:
# Python

mat = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(mat[1, 2])     # Elemento fila 1, columna 2 => 6

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
El slicing permite extraer subarrays:
</p>

In [ ]:
print(arr[1:4])      # elementos 1, 2 y 3: [20 30 40]
print(mat[:, 1])     # toda la columna 1: [2 5 8]
print(mat[0:2, 0:2]) # submatriz 2x2

<h3 style="
  font-family: 'Lato', sans-serif;
  font-weight: 600;
  text-align: justify;
  color: #3c5a80;
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34);
  font-size: 1.4em;
  margin-top: 1em;
  margin-bottom: 0.7em;
">
  2.4.2 Indexación booleana
</h3>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  Se utiliza un array booleano para seleccionar elementos que cumplen una condición.
</p>

In [ ]:
# Python

arr = np.array([10, 15, 20, 25, 30])
mask = arr > 18
print(mask)          # [False False  True  True  True]
print(arr[mask])     # [20 25 30]

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  También se puede escribir directamente:
</p>

In [ ]:
print(arr[arr % 20 == 0])  # elementos múltiplos de 20

<h3 style="
  font-family: 'Lato', sans-serif;
  font-weight: 600;
  text-align: justify;
  color: #3c5a80;
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34);
  font-size: 1.4em;
  margin-top: 1em;
  margin-bottom: 0.7em;
">
  2.4.3 Indexación avanzada con arrays enteros.
</h3>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  Se pueden pasar arrays de índices para extraer elementos arbitrarios:
</p>

In [ ]:
# Python

arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
print(arr[indices])   # [10 30 50]

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  Para arrays multidimensionales:
</p>

In [ ]:
# Python

mat = np.array([[1,2], [3,4], [5,6]])
rows = np.array([0, 1, 2])
cols = np.array([1, 0, 1])
print(mat[rows, cols])  # [2 3 6]

<h3 style="
  font-family: 'Lato', sans-serif;
  font-weight: 600;
  text-align: justify;
  color: #3c5a80;
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34);
  font-size: 1.4em;
  margin-top: 1em;
  margin-bottom: 0.7em;
">
  2.4.4 Modificación y asignación basada en indexación.
</h3>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  Los elementos seleccionados se pueden modificar:
</p>

In [ ]:
# Python

arr = np.array([1, 2, 3, 4, 5])
arr[1:4] = 10
print(arr)    # [ 1 10 10 10  5]

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  Con indexación booleana:
</p>

In [ ]:
# Python

arr = np.array([5, 10, 15, 20])
arr[arr > 10] = 100
print(arr)    # [  5  10 100 100]

---

<h2 style="
  font-family: 'Lato', sans-serif; 
  font-weight: 600; 
  text-align: justify; 
  color: #3c5a80; 
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34); 
  font-size: 1.8em; 
  margin-top: 0; 
  margin-bottom: 0.7em;
">
  2.5 Operaciones Avanzadas y Broadcasting
</h2>

<h3 style="
  font-family: 'Lato', sans-serif;
  font-weight: 600;
  text-align: justify;
  color: #3c5a80;
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34);
  font-size: 1.4em;
  margin-top: 1em;
  margin-bottom: 0.7em;
">
  2.5.1 Concepto de broadcasting
</h3>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  El broadcasting es una característica que permite realizar operaciones aritméticas entre arrays de diferentes formas (shapes) ajustando automáticamente el tamaño de sus dimensiones cuando es compatible.
</p>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  Por ejemplo, sumar un array columna a uno fila:
</p>

In [ ]:
# Python 

a = np.array([[1], [2], [3]])   # Shape (3,1)
b = np.array([10, 20, 30])      # Shape (3,)
print(a + b)

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  Salida:
</p>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
text
    
[[11 21 31]
 [12 22 32]
 [13 23 33]]
</p>

<h3 style="
  font-family: 'Lato', sans-serif;
  font-weight: 600;
  text-align: justify;
  color: #3c5a80;
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34);
  font-size: 1.4em;
  margin-top: 1em;
  margin-bottom: 0.7em;
">
  2.5.2 Reglas del broadcasting
</h3>

<ol style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  padding-left: 1.6em;
  margin-bottom: 1.5em;
">
  <li>Si las dimensiones no coinciden, se agrega dimensión 1 al principio de las formas más pequeñas.</li>
  <li>En cada dimensión, los tamaños deben ser iguales o uno de ellos debe ser 1.</li>
  <li>Si alguna dimensión es 1, el array se "extiende" para coincidir con la otra.</li>
</ol>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 1.0em;
">
  Si las condiciones no se cumplen, NumPy genera un error.
</p>

<h3 style="
  font-family: 'Lato', sans-serif;
  font-weight: 600;
  text-align: justify;
  color: #3c5a80;
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34);
  font-size: 1.4em;
  margin-top: 1.5em;
  margin-bottom: 0.7em;
">
  2.5.3 Operaciones avanzadas con broadcasting
</h3>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 1.5em;
">
  Ejemplo multiplicando un vector con fila matriz:
</p>

In [ ]:
# Python 

mat = np.array([[1, 2, 3],
                [4, 5, 6]])
vec = np.array([1, 0, 1])

result = mat * vec  # Broadcasting de vec sobre filas
print(result)

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  Salida:
</p>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
text
    
[[1 0 3]
 [4 0 6]]
</p>

<h3 style="
  font-family: 'Lato', sans-serif;
  font-weight: 600;
  text-align: justify;
  color: #3c5a80;
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34);
  font-size: 1.4em;
  margin-top: 1.5em;
  margin-bottom: 0.7em;
">
  2.5.4 Manipulación avanzada de arrays: reshape, transpose, flatten
</h3>

<ul style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  padding-left: 1.2em;
  margin-bottom: 1.5em;
">
  <li><code>reshape</code>: Cambia la forma del array sin modificar los datos. Obligatorio que el nuevo tamaño mantenga el mismo número de elementos.</li>
</ul>


In [ ]:
# Python

arr = np.arange(6)
print(arr.reshape((2, 3)))

<ul style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  padding-left: 1.2em;
  margin-bottom: 1.5em;
">
  <li><code>transpose</code>: Transpone ejes. En 2D intercambia filas y columnas.</li>
</ul>

In [ ]:
# Python

mat = np.array([[1, 2], [3, 4]])
print(mat.T)

<ul style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  padding-left: 1.2em;
  margin-bottom: 1.5em;
">
  <li><code>flatten</code>: Convierte cualquier array en 1D.</li>
</ul>

In [ ]:
#Python

mat = np.array([[1, 2], [3, 4]])
flat = mat.flatten()
print(flat)

<h2 style="
  font-family: 'Lato', sans-serif;
  font-weight: 600;
  text-align: justify;
  color: #3c5a80;
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34);
  font-size: 1.8em;
  margin-top: 1.5em;
  margin-bottom: 0.7em;
">
  2.6 Ejemplos Prácticos y Casos de Uso
</h2>

<h3 style="
  font-family: 'Lato', sans-serif;
  font-weight: 600;
  text-align: justify;
  color: #3c5a80;
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34);
  font-size: 1.4em;
  margin-top: 1em;
  margin-bottom: 0.7em;
">
  2.6.1 Álgebra lineal con NumPy
</h3>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  NumPy incluye funciones para:
</p>

<ul style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  padding-left: 1.2em;
  margin-bottom: 1.5em;
">
  <li>Producto punto: <code>np.dot(a, b)</code> o <code>a @ b</code> (Python 3.5+).</li>
  <li>Determinante: <code>np.linalg.det()</code></li>
  <li>Inversa: <code>np.linalg.inv()</code></li>
  <li>Valores y vectores propios: <code>np.linalg.eig()</code></li>
  <li>Solución de sistemas lineales: <code>np.linalg.solve(A, b)</code></li>
</ul>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  Ejemplo matriz e inversa:
</p>

In [ ]:
# Python

A = np.array([[3, 1], [1, 2]])
print("Matriz A:\n", A)

invA = np.linalg.inv(A)
print("Inversa de A:\n", invA)

# Comprobar que A * invA da identidad
print("Producto:\n", np.dot(A, invA))

<h3 style="
  font-family: 'Lato', sans-serif;
  font-weight: 600;
  text-align: justify;
  color: #3c5a80;
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34);
  font-size: 1.4em;
  margin-top: 1.5em;
  margin-bottom: 0.7em;
">
  2.6.2 Análisis y manipulación de datos
</h3>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  Suponga que se tiene un dataset numérico, NumPy facilita:
</p>

<ul style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  padding-left: 1.2em;
  margin-bottom: 1.5em;
">
  <li>Cálculo de estadísticas descriptivas.</li>
  <li>Filtrar datos usando condiciones.</li>
  <li>Transformación de datos (normalización, estandarización, etc.).</li>
</ul>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  Ejemplo simple de normalización:
</p>

In [ ]:
# Python

data = np.array([10, 15, 20, 25, 30])
normalized = (data - np.min(data)) / (np.max(data) - np.min(data))
print(normalized)

<h3 style="
  font-family: 'Lato', sans-serif;
  font-weight: 600;
  text-align: justify;
  color: #3c5a80;
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34);
  font-size: 1.4em;
  margin-top: 1.5em;
  margin-bottom: 0.7em;
">
  2.6.3 Simulación numérica y ciencias físicas
</h3>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  NumPy es apropiada para resolver ecuaciones diferenciales con métodos numéricos, generar señales, procesar imágenes, entre otros.
</p>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  Ejemplo de generación de una señal sinusoidal:
</p>


In [ ]:
# Python

t = np.linspace(0, 1, 500)   # Tiempo de 0 a 1 seg, 500 puntos
f = 5                       # Frecuencia 5 Hz
signal = np.sin(2 * np.pi * f * t)

import matplotlib.pyplot as plt
plt.plot(t, signal)
plt.title("Señal senoidal")
plt.xlabel("Tiempo [s]")
plt.ylabel("Amplitud")
plt.show()

<h3 style="
  font-family: 'Lato', sans-serif;
  font-weight: 600;
  text-align: justify;
  color: #3c5a80;
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34);
  font-size: 1.4em;
  margin-top: 1.5em;
  margin-bottom: 0.7em;
">
  2.6.4 Preparación de datos para machine learning
</h3>

<ul style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  padding-left: 1.2em;
  margin-bottom: 1.5em;
">
  <li>Conversión de datos crudos en arrays numéricos.</li>
  <li>Transformación de características (feature engineering).</li>
  <li>Manejo eficiente de grandes matrices de atributos.</li>
</ul>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 0.7em;
">
  Ejemplo para crear matriz de características y vector objetivo:
</p>

In [ ]:
# Python

X = np.array([[1, 20], [2, 25], [3, 30]])
y = np.array([0, 1, 0])  # Etiquetas

print("Matriz de entrada:\n", X)
print("Vector objetivo:\n", y)

<h1 style="
  font-family: 'Montserrat', sans-serif;
  font-weight: 700;
  text-align: center;
  color: #3c5a80;
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34);
  font-size: 2.5em;
  margin-top: 2em;
  margin-bottom: 0.7em;
">
  3. Conclusión.
</h1>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 2em;
">
  En este tutorial hemos explorado de manera integral la biblioteca NumPy como una herramienta crucial para el análisis numérico en Python. Desde su instalación hasta técnicas avanzadas como el broadcasting y la indexación sofisticada, NumPy ofrece soluciones altamente optimizadas para manipular datos multidimensionales y realizar cálculos matemáticos complejos con eficiencia y simplicidad. Hemos visto cómo crear y manipular arrays, aplicar funciones matemáticas y estadísticas, trabajar con álgebra lineal y ejemplos prácticos que ilustran su valiosa utilidad en ciencia, ingeniería y análisis de datos. Su integración con el ecosistema científico y facilidad de uso hacen de NumPy un pilar indispensable en la ciencia de datos y el análisis computacional contemporáneo, facilitando no solo la experimentación y modelado sino también la producción de código limpio y rápido.
</p>

<h1 id="referencias" style="
  font-family: 'Montserrat', sans-serif;
  font-weight: 700;
  text-align: center;
  color: #3c5a80;
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34);
  font-size: 2.5em;
  margin-top: 2em;
  margin-bottom: 0.7em;
">
  4. Referencias
</h1>

<ul style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  padding-left: 1.2em;
  margin-bottom: 2em;
">
  <li>
    Harris, C. R., Millman, K. J., van der Walt, S. J., Gommers, R., Virtanen, P., Cournapeau, D., ... &amp; Oliphant, T. E. (2020). Array programming with NumPy. <em>Nature</em>, 585(7825), 357-362. 
    <a href="https://doi.org/10.1038/s41586-020-2649-2" style="color:#1a73e8; text-decoration:none;">https://doi.org/10.1038/s41586-020-2649-2</a>
  </li>
  <li>
    Oliphant, T. E. (2006). <em>A guide to NumPy.</em> Trelgol Publishing.
  </li>
  <li>
    Van Der Walt, S., Colbert, S. C., &amp; Varoquaux, G. (2011). The NumPy array: a structure for efficient numerical computation. <em>Computing in Science &amp; Engineering</em>, 13(2), 22-30. 
    <a href="https://doi.org/10.1109/MCSE.2011.37" style="color:#1a73e8; text-decoration:none;">https://doi.org/10.1109/MCSE.2011.37</a>
  </li>
</ul>

<p style="
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  text-align: justify;
  font-size: 1.1em;
  line-height: 1.6;
  color: #2c3e50;
  margin-top: 0;
  margin-bottom: 2em;
">
  Este tutorial está diseñado para proporcionar a programadores con conocimientos básicos un camino claro, ordenado y profundo hacia el dominio de NumPy, facilitando el desarrollo de habilidades esenciales para el trabajo científico y el análisis de datos moderno.
</p>


<h1 id="referencias" style="
  font-family: 'Montserrat', sans-serif;
  font-weight: 700;
  text-align: center;
  color: #3c5a80;
  text-shadow: 3px 3px 14px rgba(60, 70, 100, 0.34);
  font-size: 2.5em;
  margin-top: 2em;
  margin-bottom: 0.7em;
">
  Gracias hasta luego
</h1>